-- use default schema sys
use sys;
-- create schema for PetCare
create schema `pet_care`;
-- use pet_care
use pet_care;

SET GLOBAL time_zone = '+00:00';
SET SESSION time_zone = '+00:00';
SELECT @@GLOBAL.time_zone, @@SESSION.time_zone;

-- CREATE TABLE APPOINTMENT
CREATE TABLE `pet_care`.`appointment` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CUSTOMERID` INT NULL,
  `PETID` INT NULL,
  `VETASSIGNMENTID` INT NOT NULL,
  `BOOKSERVICEID` INT NOT NULL,
  `CONFIRMEDAT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `CUSTOMERPHONENUMBER` VARCHAR(15) NOT NULL,
  `CUSTOMERNAME` VARCHAR(100) NOT NULL,
  `SPECIES` ENUM('DOG', 'CAT', 'BIRD', 'RABBIT') NOT NULL,
  `PURPOSEDESCRIPTION` VARCHAR(300) NOT NULL,
  `VETNOTES` VARCHAR(800) NULL,
  `TOTALPRICE` DECIMAL(10,2) NOT NULL,
  `MEDICATIONPRESCRIBED` VARCHAR(500) NULL,
  `ISPAID` BOOLEAN NOT NULL,
  `PAIDAT` DATETIME NULL,
  `PAYMENTMETHOD` ENUM('CASH', 'CARD') NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `id_UNIQUE` (`ID` ASC) VISIBLE);

-- CREATE TABLE PET
CREATE TABLE `pet_care`.`pet` (
  `ID` INT NOT NULL,
  `OWNERID` INT NOT NULL,
  `DATEOFBIRTH` DATE NOT NULL,
  `SPECIES` ENUM('DOG', 'CAT', 'BIRD', 'RABBIT') NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `GENDER` ENUM('MALE', 'FEMALE') NOT NULL,
  `DESEXED` BOOLEAN NOT NULL,
  `REGISTEREDAT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `COUNCILREGISTRATIONNUMBER` VARCHAR(45) NULL,
  `ISDECEASED` BOOLEAN NOT NULL,
  `ISSTRAY` BOOLEAN NOT NULL,
  PRIMARY KEY (`ID`));
  
  -- CREATE TABLE CUSTOMER
  CREATE TABLE `pet_care`.`customer` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `PHONENUMBER` VARCHAR(15) NOT NULL,
  `POSTCODE` VARCHAR(5) NULL,
  `REGISTEREDAT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `CURRENTPASSWORD` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE);
  
-- CREATE TABLE VET
CREATE TABLE `pet_care`.`vet` (
  `ID` INT NOT NULL,
  `FIRSTNAME` VARCHAR(50) NOT NULL,
  `LASTNAME` VARCHAR(50) NOT NULL,
  `MIDDLENAME` VARCHAR(50) NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `PHONENUMBER` VARCHAR(15) NOT NULL,
  `ISSPECIALIST` BOOLEAN NOT NULL,
  `SPECIALISTFIELD` VARCHAR(50) NULL,
  PRIMARY KEY (`ID`));
  
-- CREATE TABLE LABTESTRESULT
CREATE TABLE `pet_care`.`labtestresult` (
  `ID` INT NOT NULL,
  `ORDEREDAT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `RESULT` VARCHAR(500) NOT NULL,
  `RELEASEDAT` DATETIME NULL,
  PRIMARY KEY (`ID`));

-- CREATE TABLE MEDICALSERVICEBOOKED
CREATE TABLE `pet_care`.`medicalserviceboooked` (
  `ID` INT NOT NULL,
  `SERVICEID` INT NOT NULL,
  `RESULTID` INT NULL,
  `COSTATCONFIRMEDTIME` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`ID`, `SERVICEID`));

-- CREATE TABLE VETASSIGNMENT
CREATE TABLE `pet_care`.`vetassignment` (
  `ID` INT NOT NULL,
  `VETID` INT NOT NULL,
  `SPOTID` INT NOT NULL,
  PRIMARY KEY (`ID`));

-- CREATE TABLE 




